### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by tkotha** [tyage/video-player#9]
[Enter steps to reproduce below:]

1. press ctrl alt p
2. select mp4 file (after having set up the path to vlc, which is similar to default app path)
3. get exception screen

**Atom Version**: 0.190.0
**System**: Mac OS X 10.9.4
**Thrown From**: [video-player](https://github.com/tyage/video-player) package, v0.8.1

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/human/.atom/packages/video-player/lib/video-player-view.coffee:57

TypeError: undefined is not a function
  at VideoPlayerView.module.exports.VideoPlayerView._play (/Users/human/.atom/packages/video-player/lib/video-player-view.coffee:57:30)
  at /Users/human/.atom/packages/video-player/lib/video-player-view.coffee:47:14
  at CallbacksRegistry.module.exports.CallbacksRegistry.apply (/Applications/Atom.app/Contents/Resources/atom.asar/common/api/lib/callbacks-registry.js:35:42)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:146:30)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)

```

### Commands

```
     -7:12.8 recent-files:0 (atom-text-editor.editor.is-focused)
     -7:02.6 core:confirm (atom-text-editor.editor.mini)
     -6:06.7 application:new-file (ul.list-inline.tab-bar.inset-panel)
  2x -6:03.3 term:open-split-right (atom-text-editor.editor)
  6x -4:30.3 core:confirm (atom-text-editor.editor.mini)
     -1:05.6 pane:split-down (atom-text-editor.editor.is-focused)
     -0:59.4 pane:close (atom-text-editor.editor.is-focused)
     -0:52.4 pane:split-left (atom-text-editor.editor.is-focused)
     -0:08.0 video-player:play (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "terminal-panel",
      "autocomplete"
    ],
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "video-player": {}
}
```

### Installed Packages

```coffee
# User
atom-pair, v1.1.4
autocomplete-plus-async, v0.22.0
block-travel, v1.0.2
color-picker, v1.6.0
docblockr, v0.6.3
envygeeks-file-icons, v0.2.1
file-icons, v1.5.4
hex, v0.5.0
inline-autocomplete, v1.0.4
linter, v0.12.0
pdf-view, v0.17.0
playlist, v0.1.7
recent-files, v0.3.0
term, v0.2.2
tree-view-breadcrumb, v0.4.1
video-player, v0.8.1

# Dev
No dev packages
```

**Comment by tyage** [comment]
thank you for reporting!
closed by 1c11f29
